// File generated by github.com/ungerik/pkgreflect
package pb

import "reflect"

var Types = map[string]reflect.Type{
	"WerewolfServerClient": reflect.TypeOf((*WerewolfServerClient)(nil)).Elem(),
	"WerewolfServerServer": reflect.TypeOf((*WerewolfServerServer)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"NewWerewolfServerClient":      reflect.ValueOf(NewWerewolfServerClient),
	"RegisterWerewolfServerServer": reflect.ValueOf(RegisterWerewolfServerServer),
}

var Variables = map[string]reflect.Value{}

var Consts = map[string]reflect.Value{}
